name: .NET Core Deploy and Run

on:
  workflow_dispatch:
  push:
    branches: [ main ]
env:
  DEPLOY_PATH: "/root/GraphView"
  BUILD_SCRIPT_OUTPUT: "GraphView/bin/Debug/net7.0/linux-x64/publish"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish
        run: dotnet publish --os linux
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          strip_components: 6
      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          script: |
            screen -X -S GraphView quit
            cd GraphView
            screen -S GraphView -d -m dotnet GraphView.dll